"""
Core Platform-Agnostic Webhook API
ONLY receives normalized messages from integration layers

Returns Server-Sent Events (SSE) for real-time message streaming.
"""

import json
import asyncio
from uuid import UUID
from typing import AsyncGenerator
from fastapi import APIRouter, Depends, HTTPException, Header, status
from fastapi.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.services.bot_service import BotService
from app.core.engine import ConversationOrchestrator
from app.core.redis_manager import redis_manager
from app.config import settings
from app.schemas.webhook_schema import WebhookMessageRequest
from app.repositories.audit_log_repository import AuditLogRepository
from app.models.audit_log import AuditResult
from app.utils.exceptions import NotFoundError, SecurityServiceUnavailableError
from app.utils.logger import logger
from app.utils.responses import unauthorized, not_found, too_many_requests, service_unavailable
from app.api.webhooks.sanitization import sanitize_and_audit_webhook_input

router = APIRouter(tags=["webhooks"])


def format_sse_event(data: dict) -> str:
    """Format data as an SSE event."""
    return f"data: {json.dumps(data)}\n\n"


@router.post("/webhook/{bot_id}")
async def process_bot_message(
    bot_id: UUID,
    message_data: WebhookMessageRequest,
    x_webhook_secret: str = Header(None, alias="X-Webhook-Secret"),
    db: AsyncSession = Depends(get_db)
):
    """
    CORE PLATFORM-AGNOSTIC WEBHOOK ENDPOINT WITH SSE STREAMING

    Returns Server-Sent Events (SSE) for real-time message delivery.
    Messages stream to the client as they are generated by each node.

    **Who calls this endpoint:**
    - Chat simulator (frontend)
    - External services with SSE support
    - Testing tools

    **Authentication:**
    Requires X-Webhook-Secret header matching bot's webhook_secret

    **Request Body:**
    ```json
    {
        "channel": "test",
        "channel_user_id": "user-123",
        "message_text": "START"
    }
    ```

    **Response (SSE Stream):**
    ```
    data: {"message": "Welcome!", "index": 0}

    data: {"message": "What is your name?", "index": 1}

    data: {"done": true, "session_id": "uuid", "session_active": true}
    ```

    **SSE Event Fields:**
    - `message`: Bot message text
    - `index`: Zero-based message sequence number
    - `done`: True on final event
    - `session_id`: Session identifier
    - `session_active`: True if waiting for user input
    - `session_ended`: True if flow completed
    - `error`: Error message (if failed)
    """

    # 1. Validate webhook secret
    if not x_webhook_secret:
        logger.warning(f"Webhook request without secret header: bot={bot_id}")
        raise unauthorized("X-Webhook-Secret header is required")

    bot_service = BotService(db)
    audit_log = AuditLogRepository(db)

    # 2. Verify webhook authentication
    is_valid = await bot_service.verify_webhook_secret(bot_id, x_webhook_secret)
    if not is_valid:
        logger.warning(f"Invalid webhook secret: bot={bot_id}")
        raise unauthorized("Invalid webhook secret")

    # 3. Get bot and verify existence
    try:
        bot = await bot_service.get_bot(bot_id, check_ownership=False)
    except NotFoundError:
        logger.error(f"Bot not found: {bot_id}")
        raise not_found(f"Bot {bot_id} not found")

    # 4. Check bot status (return SSE error for inactive bot)
    if not bot.is_active():
        logger.info(f"Webhook call to inactive bot: {bot_id}")

        async def inactive_bot_stream():
            yield format_sse_event({"error": "Bot is currently inactive", "done": True})

        return StreamingResponse(
            inactive_bot_stream(),
            media_type="text/event-stream",
            headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"}
        )

    # 5. Rate limiting (channel-agnostic)
    try:
        allowed = await redis_manager.check_rate_limit_channel_user(
            message_data.channel,
            message_data.channel_user_id,
            settings.rate_limit.webhook_max,
            settings.rate_limit.webhook_window
        )
        if not allowed:
            masked_user = logger.mask_pii(message_data.channel_user_id, "user_id")
            logger.warning(
                f"Rate limit exceeded",
                channel=message_data.channel,
                user=masked_user
            )
            await audit_log.log_security_event(
                action="rate_limit_exceeded",
                user_id=masked_user,
                result=AuditResult.BLOCKED,
                event_metadata={
                    "bot_id": str(bot_id),
                    "channel": message_data.channel
                }
            )
            raise too_many_requests("Too many requests. Please try again later.")
    except SecurityServiceUnavailableError as e:
        logger.error(f"Security service unavailable: {e.feature}", bot_id=str(bot_id))
        raise service_unavailable("Service temporarily unavailable. Please try again later.")

    # 6. Input Sanitization (Layer 1 + Layer 3)
    is_safe, sanitized_message, error_message = await sanitize_and_audit_webhook_input(
        message=message_data.message_text,
        bot_id=bot_id,
        channel=message_data.channel,
        channel_user_id=message_data.channel_user_id,
        audit_log=audit_log
    )

    if not is_safe:
        async def pattern_error_stream():
            yield format_sse_event({
                "error": error_message,
                "done": True
            })

        return StreamingResponse(
            pattern_error_stream(),
            media_type="text/event-stream",
            headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"}
        )

    message_data.message_text = sanitized_message

    # 7. Process through conversation engine with SSE streaming
    async def generate_sse_stream() -> AsyncGenerator[str, None]:
        """Generate SSE events as messages are produced by the engine."""
        message_queue: asyncio.Queue = asyncio.Queue()
        message_index = 0

        async def on_message(message: str, is_final: bool) -> None:
            """Callback invoked by engine for each message."""
            nonlocal message_index
            if message:
                await message_queue.put({"message": message, "index": message_index})
                message_index += 1
            if is_final:
                await message_queue.put(None)  # Sentinel to signal completion

        async def run_engine():
            """Run the engine and put result on queue when done."""
            try:
                orchestrator = ConversationOrchestrator(db)
                result = await orchestrator.process_message(
                    channel=message_data.channel,
                    channel_user_id=message_data.channel_user_id,
                    bot_id=bot_id,
                    message=message_data.message_text,
                    message_callback=on_message
                )
                # Put final result for done event
                await message_queue.put({
                    "_done": True,
                    "session_id": result.get("session_id"),
                    "session_active": result.get("session_active", False),
                    "session_ended": result.get("session_ended", False)
                })
            except Exception as e:
                logger.error(f"Engine error: {e}", bot_id=str(bot_id), exc_info=True)
                await message_queue.put({
                    "_error": True,
                    "error": "An error occurred processing your message."
                })

        # Start engine in background task
        engine_task = asyncio.create_task(run_engine())

        try:
            while True:
                item = await message_queue.get()

                if item is None:
                    # Sentinel from callback - engine is finishing, wait for result
                    continue

                if item.get("_done"):
                    # Final done event
                    yield format_sse_event({
                        "done": True,
                        "session_id": item.get("session_id"),
                        "session_active": item.get("session_active"),
                        "session_ended": item.get("session_ended")
                    })
                    break

                if item.get("_error"):
                    # Error event
                    yield format_sse_event({
                        "error": item.get("error"),
                        "done": True
                    })
                    break

                # Regular message event
                yield format_sse_event(item)

        finally:
            # Ensure engine task completes
            if not engine_task.done():
                engine_task.cancel()
                try:
                    await engine_task
                except asyncio.CancelledError:
                    pass

        logger.info(
            "SSE stream completed",
            bot_id=str(bot_id),
            channel=message_data.channel
        )

    return StreamingResponse(
        generate_sse_stream(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no"  # Disable nginx buffering
        }
    )
